DROP TABLE DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD;

CREATE TABLE DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
(
  ACS_CODE_UTILI_BD               VARCHAR2(128 ),
  ACS_NOM_BASE                    VARCHAR2(50 ),
  ACS_NOM_PROGR                   VARCHAR2(48 ),
  ACS_NOM_MODUL                   VARCHAR2(64 ),
  ACS_NBR_LOGIC_READS_SESSI       NUMBER,
  ACS_NBR_CONSI_GETS              NUMBER,
  ACS_NBR_PHYSI_READS             NUMBER,
  ACS_NBR_PHYSI_WRITE             NUMBER,
  ACS_NBR_EXECU_COUNT             NUMBER,
  ACS_NBR_CONSI_READ_GETS         NUMBER,
  ACS_NBR_BYTE_ENVOI_CLIEN        NUMBER,
  ACS_NBR_BYTE_RECU_CLIEN         NUMBER,
  ACS_NBR_ROUND_TRIP_CLIEN        NUMBER,
  ACS_NBR_LOGIC_READ_BYTE_CACHE   NUMBER,
  ACS_NBR_PHYSI_READ_TOTAL_BYTE   NUMBER,
  ACS_NBR_BYTE_ENVOI_DB_LINK      NUMBER,
  ACS_NBR_BYTE_RECU_DB_LINK       NUMBER,
  ACS_NBR_ROUND_TRIP_DB_LINK      NUMBER,
  ACS_NBR_UNDO_CHANG_VECTO_SIZE  NUMBER
)
TABLESPACE DRIAUDITD01
LOGGING 
NOCOMPRESS 
NOCACHE;

-- 
/*
DROP TABLE DRI_AUDIT.DRI_AUDIT_STATI_DESC;

CREATE TABLE DRI_AUDIT.DRI_AUDIT_STATI_DESC
(
  AST_NO         NUMBER                         NOT NULL,
  AST_NOM        VARCHAR2(64 )              NOT NULL,
  AST_NOM_COLON  VARCHAR2(64 ),
  AST_DESC 		 VARCHAR2(50)
)
TABLESPACE DRIAUDITD01;

INSERT INTO DRI_AUDIT.DRI_AUDIT_STATI_DESC(AST_NO,AST_NOM,AST_NOM_COLON)
SELECT * FROM DRI_AUDIT.DRI_AUDIT_STATI;
*/