DROP TABLE DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD;

CREATE TABLE DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
( ACS_NO_IDENT                    NUMBER  ,
  ACS_NO_UNIQU_SESSI              VARCHAR2(30 CHAR) NOT NULL,
  ACS_CODE_UTILI_BD               VARCHAR2(128 ),
  ACS_NOM_BASE                    VARCHAR2(50 ),
  ACS_NOM_SERVI                   VARCHAR2(64 CHAR),
  ACS_DATE_LOGON                  DATE,
  ACS_NOM_PROGR                   VARCHAR2(48 ),
  ACS_NOM_MODUL                   VARCHAR2(64 ),
  ACS_NBR_LOGIC_READS_SESSI       NUMBER,
  ACS_NBR_CONSI_GETS              NUMBER,
  ACS_NBR_PHYSI_READS             NUMBER,
  ACS_NBR_PHYSI_WRITE             NUMBER,
  ACS_NBR_EXECU_COUNT             NUMBER,
  ACS_NBR_CONSI_READ_GETS         NUMBER,
  ACS_NBR_BYTE_ENVOI_CLIEN        NUMBER,
  ACS_NBR_BYTE_RECU_CLIEN         NUMBER,
  ACS_NBR_ROUND_TRIP_CLIEN        NUMBER,
  ACS_NBR_LOGIC_READ_BYTE_CACHE   NUMBER,
  ACS_NBR_PHYSI_READ_TOTAL_BYTE   NUMBER,
  ACS_NBR_BYTE_ENVOI_DB_LINK      NUMBER,
  ACS_NBR_BYTE_RECU_DB_LINK       NUMBER,
  ACS_NBR_ROUND_TRIP_DB_LINK      NUMBER,
  ACS_NBR_UNDO_CHANG_VECTO_SIZE  NUMBER
)
TABLESPACE DRIAUDITNL01
NOLOGGING 
NOCOMPRESS 
NOCACHE;

CREATE INDEX DRI_AUDIT.ACSB_CUB_I ON DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD(ACS_CODE_UTILI_BD,ACS_NOM_BASE)
NOLOGGING
TABLESPACE DRIAUDITNL01;

drop index DRI_AUDIT.ACSB_DATE_TRUNC_I;
CREATE INDEX DRI_AUDIT.ACSB_DATE_TRUNC_I ON DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
(TRUNC(ACS_DATE_LOGON))
NOLOGGING
TABLESPACE DRIAUDITNL01;

drop index DRI_AUDIT.ACSB_DATE_MM_TRUNC_I;
CREATE INDEX DRI_AUDIT.ACSB_DATE_MM_TRUNC_I ON DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
(TRUNC(ACS_DATE_LOGON,'MM'))
NOLOGGING
TABLESPACE DRIAUDITNL01;


CREATE INDEX DRI_AUDIT.ACSB_CU3_TRUNC_I ON DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
(SUBSTR(ACS_CODE_UTILI_BD,0,3))
NOLOGGING
TABLESPACE DRIAUDITNL01;

CREATE INDEX DRI_AUDIT.ACSB_NB_I ON DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD(ACS_NOM_BASE)
NOLOGGING
TABLESPACE DRIAUDITNL01;


CREATE TABLE DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD_TRI AS 
SELECT DISTINCT ACS_NOM_BASE, '1' ORD_TRI
FROM DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD;

-- 
