DROP TABLE DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD;

CREATE TABLE DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
( ACS_NO_IDENT                    NUMBER  ,
  ACS_NO_UNIQU_SESSI              VARCHAR2(30 CHAR) NOT NULL,
  ACS_CODE_UTILI_BD               VARCHAR2(128 ),
  ACS_NOM_BASE                    VARCHAR2(50 ),
  ACS_NOM_SERVI                   VARCHAR2(64 CHAR),
  ACS_DATE_LOGON                  DATE,
  ACS_NOM_PROGR                   VARCHAR2(48 ),
  ACS_NOM_MODUL                   VARCHAR2(64 ),
  ACS_NBR_LOGIC_READS_SESSI       NUMBER,
  ACS_NBR_CONSI_GETS              NUMBER,
  ACS_NBR_PHYSI_READS             NUMBER,
  ACS_NBR_PHYSI_WRITE             NUMBER,
  ACS_NBR_EXECU_COUNT             NUMBER,
  ACS_NBR_CONSI_READ_GETS         NUMBER,
  ACS_NBR_BYTE_ENVOI_CLIEN        NUMBER,
  ACS_NBR_BYTE_RECU_CLIEN         NUMBER,
  ACS_NBR_ROUND_TRIP_CLIEN        NUMBER,
  ACS_NBR_LOGIC_READ_BYTE_CACHE   NUMBER,
  ACS_NBR_PHYSI_READ_TOTAL_BYTE   NUMBER,
  ACS_NBR_BYTE_ENVOI_DB_LINK      NUMBER,
  ACS_NBR_BYTE_RECU_DB_LINK       NUMBER,
  ACS_NBR_ROUND_TRIP_DB_LINK      NUMBER,
  ACS_NBR_UNDO_CHANG_VECTO_SIZE  NUMBER
)
TABLESPACE DRIAUDITNL01
NOLOGGING 
NOCOMPRESS 
NOCACHE;

CREATE INDEX DRI_AUDIT.ACSB_CUB_I ON DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD(ACS_CODE_UTILI_BD,ACS_NOM_BASE)
NOLOGGING
TABLESPACE DRIAUDITNL01;

drop index DRI_AUDIT.ACSB_DATE_TRUNC_I;
CREATE INDEX DRI_AUDIT.ACSB_DATE_TRUNC_I ON DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
(TRUNC(ACS_DATE_LOGON))
NOLOGGING
TABLESPACE DRIAUDITNL01;

drop index DRI_AUDIT.ACSB_DATE_MM_TRUNC_I;
CREATE INDEX DRI_AUDIT.ACSB_DATE_MM_TRUNC_I ON DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
(TRUNC(ACS_DATE_LOGON,'MM'))
NOLOGGING
TABLESPACE DRIAUDITNL01;


CREATE INDEX DRI_AUDIT.ACSB_CU3_TRUNC_I ON DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
(SUBSTR(ACS_CODE_UTILI_BD,0,3))
NOLOGGING
TABLESPACE DRIAUDITNL01;

CREATE INDEX DRI_AUDIT.ACSB_NB_I ON DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD(ACS_NOM_BASE)
NOLOGGING
TABLESPACE DRIAUDITNL01;


CREATE TABLE DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD_TRI AS 
SELECT DISTINCT ACS_NOM_BASE, '1' ORD_TRI
FROM DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD;

-- 

CREATE TABLE DRI_AUDIT.DRI_AUDIT_CONNE_REGRO_2023
(
  ACR_NO_IDENT                    NUMBER        NOT NULL,
  ACR_NO_UNIQU_SESSI              VARCHAR2(30 CHAR) NOT NULL,
  ACR_CODE_UTILI_BD               VARCHAR2(128 CHAR),
  ACR_CODE_UTILI_OS               VARCHAR2(30 CHAR),
  ACR_NO_UTILI                    VARCHAR2(30 CHAR),
  ACR_DATE_LOGON                  DATE,
  ACR_DATE_LOGOF                  DATE,
  ACR_NOM_BASE                    VARCHAR2(50 CHAR),
  ACR_CODE_SYSTE                  VARCHAR2(7 CHAR),
  ACR_NO_INSTA                    NUMBER,
  ACR_NO_SID                      NUMBER,
  ACR_NO_SERIA                    NUMBER,
  ACR_NO_PID                      NUMBER,
  ACR_NO_SPID                     NUMBER,
  ACR_NOM_MACHI                   VARCHAR2(64 CHAR),
  ACR_NOM_TERMI                   VARCHAR2(30 CHAR),
  ACR_NOM_PROGR                   VARCHAR2(48 CHAR),
  ACR_NOM_MODUL                   VARCHAR2(64 CHAR),
  ACR_NBR_LOGIC_READS_SESSI       NUMBER,
  ACR_NBR_UGA_MEMOR_SESSI         NUMBER,
  ACR_NBR_PGA_MEMOR_SESSI         NUMBER,
  ACR_NBR_CONSI_GETS              NUMBER,
  ACR_NBR_PHYSI_READS             NUMBER,
  ACR_NBR_PHYSI_WRITE             NUMBER,
  ACR_NBR_CONSI_READ_GETS         NUMBER,
  ACR_NBR_TABLE_FETCH_BY_ROWID    NUMBER,
  ACR_NBR_BYTE_ENVOI_CLIEN        NUMBER,
  ACR_NBR_BYTE_RECU_CLIEN         NUMBER,
  ACR_NBR_ROUND_TRIP_CLIEN        NUMBER,
  ACR_NBR_SORT_DISK               NUMBER,
  ACR_NO_PROCE                    VARCHAR2(24 CHAR),
  ACR_NBR_BYTE_ENVOI_DB_LINK      NUMBER,
  ACR_NBR_BYTE_RECU_DB_LINK       NUMBER,
  ACR_NBR_ROUND_TRIP_DB_LINK      NUMBER,
  ACR_NOM_SERVI                   VARCHAR2(64 CHAR),
  ACR_TYPE_IDENT                  VARCHAR2(30 CHAR),
  ACR_CODE_UTILI_PROXY            VARCHAR2(30 CHAR),
  ACR_NO_IDENT_USAGE_PROXY        NUMBER,
  ACR_NBR_CPU_USED_BY_THIS_SESSI  NUMBER,
  ACR_NBR_REDO_ENTRI              NUMBER,
  ACR_NBR_REDO_SIZE               NUMBER,
  ACR_NBR_FILE_IO_WAIT_TIME       NUMBER,
  ACR_NBR_GC_CR_BLOCK_RECEI       NUMBER,
  ACR_NBR_GC_CR_BLOCK_RECEI_TIME  NUMBER,
  ACR_NBR_GC_CURRE_BLOCK_RECEI    NUMBER,
  ACR_NBR_GC_CURRE_BLOCK_RECEI_T  NUMBER,
  ACR_NBR_GC_CPU_USED_BY_SESSI    NUMBER,
  ACR_NBR_EFFEC_IO_TIME           NUMBER,
  ACR_NBR_TEMP_SPACE_ALLOC_BYTE   NUMBER,
  ACR_NBR_UNDO_CHANG_VECTO_SIZE   NUMBER,
  ACR_NBR_SESSI_UGA_MEMOR_MAX     NUMBER,
  ACR_NBR_SESSI_PGA_MEMOR_MAX     NUMBER,
  ACR_NBR_TABLE_SCAN_ROWS_GOTTE   NUMBER,
  ACR_NBR_TABLE_SCAN_BLOCK_GOTTE  NUMBER,
  ACR_NBR_OPENE_CURSO_CUMUL       NUMBER,
  ACR_NBR_PHYSI_READ_TOTAL_IO     NUMBER,
  ACR_NBR_PHYSI_READ_TOTAL_MULTI  NUMBER,
  ACR_NBR_PHYSI_READ_TOTAL_BYTE   NUMBER,
  ACR_NBR_CELL_PHYSI_IO_INTER     NUMBER,
  ACR_NBR_PARSE_TIME_CPU          NUMBER,
  ACR_NBR_PARSE_TIME_ELAPS        NUMBER,
  ACR_NBR_PARSE_COUNT_TOTAL       NUMBER,
  ACR_NBR_PARSE_COUNT_HARD        NUMBER,
  ACR_NBR_PARSE_COUNT_FAILU       NUMBER,
  ACR_NBR_PARSE_COUNT_DESCR       NUMBER,
  ACR_NBR_EXECU_COUNT             NUMBER,
  ACR_NBR_SORTS_MEMORY            NUMBER,
  ACR_NBR_SORTS_ROWS              NUMBER,
  ACR_NBR_DB_BLOCK_GETS           NUMBER,
  ACR_NBR_DB_BLOCK_GETS_CACHE     NUMBER,
  ACR_NBR_CONSI_GETS_CACHE        NUMBER,
  ACR_NBR_LOGIC_READ_BYTE_CACHE   NUMBER,
  ACR_NBR_PHYSI_READ_CACHE        NUMBER,
  ACR_NBR_PHYSI_READ_IO_REQUE     NUMBER,
  ACR_VAL_CLIENT_INFO             VARCHAR2(64 CHAR)
)
TABLESPACE DRIAUDITNL01
PCTFREE    10
INITRANS   1
MAXTRANS   255
NOLOGGING 
NOCOMPRESS 
NOCACHE;