-------  TEST 1 
------- https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/statistics-descriptions-2.html 

DELETE DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD;
INSERT INTO DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
SELECT  ACO_CODE_UTILI_BD             
        ,ACO_NOM_PROGR                 
        ,ACO_NOM_MODUL                 
        ,ACO_NBR_LOGIC_READS_SESSI     
        ,ACO_NBR_CONSI_GETS            
        ,ACO_NBR_PHYSI_READS           
        ,ACO_NBR_PHYSI_WRITE           
        ,ACO_NBR_EXECU_COUNT           
        ,ACO_NBR_CONSI_READ_GETS       
        ,ACO_NBR_BYTE_ENVOI_CLIEN      
        ,ACO_NBR_BYTE_RECU_CLIEN       
        ,ACO_NBR_ROUND_TRIP_CLIEN      
        ,ACO_NBR_LOGIC_READ_BYTE_CACHE 
        ,ACO_NBR_PHYSI_READ_TOTAL_BYTE 
        ,ACO_NBR_BYTE_ENVOI_DB_LINK    
        ,ACO_NBR_BYTE_RECU_DB_LINK     
        ,ACO_NBR_ROUND_TRIP_DB_LINK    
        ,ACO_NBR_UNDO_CHANG_VECTO_SIZE
FROM 	DRI_AUDIT_CONNE
WHERE   SUBSTR(ACO_CODE_UTILI_BD,0,3) ='XAI'
AND     ACO_DATE_LOGOF IS NOT NULL;	


SELECT   ROUND(SUM(ACS_NBR_BYTE_ENVOI_CLIEN)/1024/1024  ,2)  NBR_MEG_ENVOI_CLIEN   
        ,ROUND(SUM(ACS_NBR_BYTE_RECU_CLIEN )/1024/1024  ,2)  NBR_MEG_RECU_CLIEN   
        ,ROUND(SUM(ACS_NBR_ROUND_TRIP_CLIEN)     		,2)  NBR_ROUND_TRIP_CLIEN
		,ROUND(SUM(ACS_NBR_BYTE_ENVOI_DB_LINK)/1024/1024,2)  NBR_MEG_ENVOI_DB_LINK
		,ROUND(SUM(ACS_NBR_BYTE_RECU_DB_LINK)/1024/1024 ,2)  NBR_MEG_RECU_DB_LINK
		,ROUND(SUM(ACS_NBR_ROUND_TRIP_DB_LINK)          ,2)  NBR_ROUND_TRIP_DB_LINK
FROM DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD;

-------  TEST 2 
DELETE DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD;
INSERT INTO DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
SELECT   SUBSTR(ACO_CODE_UTILI_BD,0,3) ACO_CODE_UTILI_BD            
        ,ACO_NOM_PROGR                 
        ,ACO_NOM_MODUL                 
        ,ACO_NBR_LOGIC_READS_SESSI     
        ,ACO_NBR_CONSI_GETS            
        ,ACO_NBR_PHYSI_READS           
        ,ACO_NBR_PHYSI_WRITE           
        ,ACO_NBR_EXECU_COUNT           
        ,ACO_NBR_CONSI_READ_GETS       
        ,ACO_NBR_BYTE_ENVOI_CLIEN      
        ,ACO_NBR_BYTE_RECU_CLIEN       
        ,ACO_NBR_ROUND_TRIP_CLIEN      
        ,ACO_NBR_LOGIC_READ_BYTE_CACHE 
        ,ACO_NBR_PHYSI_READ_TOTAL_BYTE 
        ,ACO_NBR_BYTE_ENVOI_DB_LINK    
        ,ACO_NBR_BYTE_RECU_DB_LINK     
        ,ACO_NBR_ROUND_TRIP_DB_LINK    
        ,ACO_NBR_UNDO_CHANG_VECTO_SIZE
FROM 	DRI_AUDIT_CONNE
WHERE     ACO_DATE_LOGOF IS NOT NULL;	
COMMIT;

SELECT   ACS_CODE_UTILI_BD
        ,ROUND(SUM(ACS_NBR_BYTE_ENVOI_CLIEN)/1024/1024  ,2)  NBR_MEG_ENVOI_CLIEN   
        ,ROUND(SUM(ACS_NBR_BYTE_RECU_CLIEN )/1024/1024  ,2)  NBR_MEG_RECU_CLIEN   
        ,ROUND(SUM(ACS_NBR_ROUND_TRIP_CLIEN)     		,2)  NBR_ROUND_TRIP_CLIEN
		,ROUND(SUM(ACS_NBR_BYTE_ENVOI_DB_LINK)/1024/1024,2)  NBR_MEG_ENVOI_DB_LINK
		,ROUND(SUM(ACS_NBR_BYTE_RECU_DB_LINK)/1024/1024 ,2)  NBR_MEG_RECU_DB_LINK
		,ROUND(SUM(ACS_NBR_ROUND_TRIP_DB_LINK)          ,2)  NBR_ROUND_TRIP_DB_LINK
FROM DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
GROUP BY ACS_CODE_UTILI_BD
ORDER BY 1;
-------  TEST 3
TRUNCATE TABLE  DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD;
INSERT INTO DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
SELECT   ACR_CODE_UTILI_BD  
        ,ACR_NOM_BASE           
        ,ACR_NOM_PROGR                 
        ,ACR_NOM_MODUL                 
        ,ACR_NBR_LOGIC_READS_SESSI     
        ,ACR_NBR_CONSI_GETS            
        ,ACR_NBR_PHYSI_READS           
        ,ACR_NBR_PHYSI_WRITE           
        ,ACR_NBR_EXECU_COUNT           
        ,ACR_NBR_CONSI_READ_GETS       
        ,ACR_NBR_BYTE_ENVOI_CLIEN      
        ,ACR_NBR_BYTE_RECU_CLIEN       
        ,ACR_NBR_ROUND_TRIP_CLIEN      
        ,ACR_NBR_LOGIC_READ_BYTE_CACHE 
        ,ACR_NBR_PHYSI_READ_TOTAL_BYTE 
        ,ACR_NBR_BYTE_ENVOI_DB_LINK    
        ,ACR_NBR_BYTE_RECU_DB_LINK     
        ,ACR_NBR_ROUND_TRIP_DB_LINK    
        ,ACR_NBR_UNDO_CHANG_VECTO_SIZE
FROM 	DRI_AUDIT_CONNE_REGRO
WHERE   ROWNUM < 100000 
AND  ACR_CODE_UTILI_BD NOT IN ('SYSMAN','SYS','RDBMS','MGMT_VIEW','SYSRAC','OPS$OCS$B1','SYSMAN_MDS')
AND ACR_DATE_LOGOF IS NOT NULL;	
COMMIT;

CREATE VIEW DRI_AUDIT_CONNE_STIBD_VUE AS 
SELECT   SUBSTR(ACS_CODE_UTILI_BD,0,3) CODE_UTILI_BD   
        ,ROUND(SUM(ACS_NBR_BYTE_ENVOI_CLIEN)/1024/1024  ,2)  NBR_MEG_ENVOI_CLIEN   
        ,ROUND(SUM(ACS_NBR_BYTE_RECU_CLIEN )/1024/1024  ,2)  NBR_MEG_RECU_CLIEN   
        ,ROUND(SUM(ACS_NBR_ROUND_TRIP_CLIEN)     		,2)  NBR_ROUND_TRIP_CLIEN
		,ROUND(SUM(ACS_NBR_BYTE_ENVOI_DB_LINK)/1024/1024,2)  NBR_MEG_ENVOI_DB_LINK
		,ROUND(SUM(ACS_NBR_BYTE_RECU_DB_LINK)/1024/1024 ,2)  NBR_MEG_RECU_DB_LINK
		,ROUND(SUM(ACS_NBR_ROUND_TRIP_DB_LINK)          ,2)  NBR_ROUND_TRIP_DB_LINK
FROM DRI_AUDIT.DRI_AUDIT_CONNE_STATS_IBD
GROUP BY SUBSTR(ACS_CODE_UTILI_BD,0,3)
ORDER BY 1;